services:
  # 后端服务
  backend:
    build: ./gnext-backend  # 指向后端 Dockerfile 所在目录
    # 如果要开机重启 restart: always
    environment:   # 注入后端的运行时环境变量
      - PORT=8080
      - ENV=production

  # 前端服务
  frontend:
    build:
      context: ./gnext-frontend # 指向前端 Dockerfile 所在目录
      args:   # 为前端注入构建时环境变量
        - NEXT_PUBLIC_API_BASE_URL=/api
    # 如果要开机重启 restart: always
    environment:      # 注入前端的运行时环境变量
      - NODE_ENV=production

  # Nginx 服务
  nginx:
    image: nginx:latest # 直接使用官方 Nginx 镜像
    ports:
      - "80:80" # 服务器80端口映射到Nginx容器80端口
    volumes: # 将本地的nginx.conf文件挂载到容器内部对应的路径
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:    # 确保在 Nginx 启动前，前后端服务已经启动
      - backend
      - frontend
    # 如果要开机重启 restart: always